#ifndef _LEPTON_SYS_H_
#define _LEPTON_SYS_H_

#include "LEPTON_Types.h"
#include "LEPTON_ErrorCodes.h"

typedef enum LEP_SYS_TELEMETRY_ENABLE_STATE_E_TAG
{
   LEP_TELEMETRY_DISABLED = 0,
   LEP_TELEMETRY_ENABLED,
   LEP_END_TELEMETRY_ENABLE_STATE

}LEP_SYS_TELEMETRY_ENABLE_STATE_E, *LEP_SYS_TELEMETRY_ENABLE_STATE_E_PTR;

typedef LEP_UINT64  LEP_SYS_FLIR_SERIAL_NUMBER_T, *LEP_SYS_FLIR_SERIAL_NUMBER_T_PTR;

extern LEP_RESULT LEP_GetSysFlirSerialNumber( LEP_CAMERA_PORT_DESC_T_PTR portDescPtr,
                                              LEP_SYS_FLIR_SERIAL_NUMBER_T_PTR sysSerialNumberBufPtr );
extern LEP_RESULT LEP_GetSysTelemetryEnableState(LEP_CAMERA_PORT_DESC_T_PTR portDescPtr,
	LEP_SYS_TELEMETRY_ENABLE_STATE_E_PTR enableStatePtr);

#endif // _LEPTON_SYS_H_
